name: Bug report for the documentation
description: File a bug report for the documentation website
labels: [bug, documentation]
body:
  - type: markdown
    attributes:
      value: |
        This repo contains the source for the [React Native for Windows website](https://aka.ms/reactnative), as well as various [code samples](https://github.com/microsoft/react-native-windows-samples/tree/main/samples) for those platforms. Issues on this repo should be constrained to problems/suggestions for the website and the samples. If you have an issue with the platforms themselves, you can file your issues here:
        - [React Native for Windows](https://github.com/microsoft/react-native-windows/issues/new/choose)
        - [React Native for macOS](https://github.com/microsoft/react-native-macos/issues/new/choose)

        Your issue will be triaged according to [this process](https://github.com/microsoft/react-native-windows/wiki/Triage-Process).
  - type: input
    validations:
      required: true
    attributes:
      label: Page url
      description: What page did you have an issue with?
      placeholder: https://microsoft.github.io/react-native-windows/docs/getting-started
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem Description
      description: Please enter a description of the issue.
