nodeLinker: node-modules
nmHoistingLimits: workspaces

npmRegistryServer: "https://pkgs.dev.azure.com/ms/react-native/_packaging/react-native-public/npm/registry/"
npmAlwaysAuth: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
