name: RNW Samples Production CI $(Date:yyyyMMdd).$(Rev:r)

trigger: none
pr: none

variables:
  - name: Codeql.Enabled
    value: true
  - name: Codeql.Cadence
    value: 120 # In hours, default to only run every 5 days

pool:
  name: rnw-pool-4
  demands: ImageOverride -equals rnw-img-vs2022-node18

steps:
  - checkout: self
    clean: false

  - script: yarn install --frozen-lockfile
    displayName: Yarn Install (Website)
    workingDirectory: ./website
  
  - script: yarn build
    displayName: Yarn Build (Website)
    workingDirectory: ./website
